### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by arski** [crate/elasticsearch-inout-plugin#39]
Hi, I can see from the changes.txt that this works with at least ES 0.90, but what about lower versions, will it work with anything before 0.90 and if so then any idea up to what? I've an old server with 0.20.2 (yikes) and wondering if this is worth trying out at all.

Might be worth adding a "minimum ES requirement" mention somewhere in the readme if there is one.

Cheers

**Comment by arski** [comment]
OK, your code uses org.elasticsearch.index.fieldvisitor.FieldsVisitor which was introduced in 0.90, so anything before that wouldn't work. Might want to add that to your readme just so that it's clear :)

Cheers

**Comment by mfussenegger** [comment]
I think the 0.2.0 release was compatible with ES 0.20. So you might give that a try.

**Comment by arski** [comment]
where can I find it? I see only 0.4.0 and 0.5.0 tags :(

**Comment by mfussenegger** [comment]
Sorry the tag was missing. I've added it. Please note that 0.2.0 lacks quite some functionality. But _export and _import is there.

**Comment by arski** [comment]
Thanks! It installed and ES worked after restart, and it seems to be using _export, though not outputting anything. Maybe the command syntax was different back then? I'm trying `curl -X POST 'http://localhost:9200/_export' -d '{"fields": ["_id"], "output_file": "/tmp/dump-${index}-${shard}"}'` returns `curl: (52) Empty reply from server`.

Any suggestions? Or should I crawl through the code myself :)

**Comment by mfussenegger** [comment]
On a first glance that looks about correct.

The readme for 0.2.0 is available on github https://github.com/crate/elasticsearch-inout-plugin/tree/0.2.0

**Comment by arski** [comment]
yea I guess it was something to do with a fairly empty test instance I was running it on.. seems to install anyway and we upgraded to 0.90 now, so I'll leave this to another lost 0.20 soul to reopen if needed :)
