### ISSUE TITLE
Corrupt exception during _export

### ISSUE THREAD

**Issue by arski** [crate/elasticsearch-inout-plugin#41]
Hi again, I'm getting something like the following in my _export output: `"_shards":{"total":5,"successful":3,"failed":2,"failures":[{"index":"paperstore","shard":4,"reason":"BroadcastShardOperationFailedException[[paperstore][4] ]; nested: RemoteTransportException[Failed to deserialize exception response from stream]; nested: TransportSerializationException[Failed to deserialize exception response from stream]; nested: StreamCorruptedException[unexpected end of block data]; "},{"index":"paperstore","shard":0,"reason":"BroadcastShardOperationFailedException[[paperstore][0] ]; nested: RemoteTransportException[Failed to deserialize exception response from stream]; nested: TransportSerializationException[Failed to deserialize exception response from stream]; nested: StreamCorruptedException[unexpected end of block data]; "}`

Any idea how I could at least make the exception show up properly so I could see what's going wrong there?

**Comment by mfussenegger** [comment]
Can you add the request you were using that resulted in that error?

The problem with the exception is that it's sometimes generated on another node than the one you sent the request too. Which means that the exception is serialized from node X to node Y and in that process there can also be errors or information can be lost. Depending on the exception.

The best option is usually to start two nodes locally in debug mode and take a look at the stacktrace.

**Comment by arski** [comment]
Was a simple export, and yea fixed it by setting two of our nodes to exact exact same version of jvm.. bit of a pain that, but works now. Cheers!

**Comment by arski** [comment]
PS. The error itself turned out to be a missing export location on one of the nodes fwiw.
